spring:
  thymeleaf.cache: false

server:
  context-path: /

logging:
  config: classpath:log-config.xml

# This value is inyected for an example
index:
  view.text:
    greeting: Hello World From Spring Boot Groovy!

spring.datasource.url: jdbc:h2:data_files