spring:
  thymeleaf.cache: false

server:
  context-path: /

logging:
  config: classpath:log-config.xml

# This value is inyected for an example
index:
  view.text:
    greeting: Hello  From Spring Boot 2.4.4 Groovy 2.5.14 !

spring.datasource.url: jdbc:h2:data_files